# Generated by Django 3.0.4 on 2020-04-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobaccos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.IntegerField(default=0)),
                ('author_name', models.CharField(max_length=100)),
                ('author_link', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1500)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='tobacco',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
