# Generated by Django 3.0.4 on 2020-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobaccos', '0002_auto_20200404_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='description',
            field=models.TextField(verbose_name='stuff'),
        ),
    ]
