# Generated by Django 3.0.4 on 2020-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobaccos', '0004_auto_20200409_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='structure',
            field=models.CharField(max_length=1000),
        ),
    ]
