# Generated by Django 3.0.4 on 2020-04-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobaccos', '0005_auto_20200409_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tobacco',
            old_name='favour',
            new_name='flavour',
        ),
        migrations.RenameField(
            model_name='tobacco',
            old_name='favour_type',
            new_name='flavour_type',
        ),
    ]
